name: merlin
description: Merlin is a STROBE-based transcript construction for zero-knowledge proofs.
version: 1.0.3
repository: https://github.com/justkawal/merlin

environment:
  sdk: ^3.1.5

dependencies:
  strobe: ^1.0.4

dev_dependencies:
  convert: ^3.1.1
  lints: ^3.0.0
  test: ^1.21.0
