name: merlin
description: A starting point for Dart libraries or applications.
version: 1.0.1
repository: https://github.com/justkawal/merlin

environment:
  sdk: ^3.1.5

dependencies:
  strobe: ^1.0.1

dev_dependencies:
  convert: ^3.1.1
  lints: ^3.0.0
  test: ^1.21.0
